spring:
  application:
    name: caraiva-tours-hub

  profiles:
    active: dev

  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: ${MAIL_USERNAME}
      password: ${MAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

app:
  security:
    jwt:
      token:
        secret-key: ${JWT_SECRET_KEY}
        expire-length: 3600000

spring-doc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true