spring:
  application:
    name: caraiva-tours-hub

  profiles:
    active: dev

app:
  security:
    jwt:
      token:
        secret-key: ${JWT_SECRET_KEY}
        expire-length: 3600000
  dashboard:
    sse:
      heartbeat-interval: 60000
      
  bootstrap-admin:
    enabled: ${BOOTSTRAP_ADMIN_ENABLED:false}
    user-name: ${BOOTSTRAP_ADMIN_USERNAME:}
    full-name: ${BOOTSTRAP_ADMIN_FULL_NAME:}
    email: ${BOOTSTRAP_ADMIN_EMAIL:}
spring-doc:
  paths-to-match: /**
  swagger-ui:
    use-root-path: true
